import type {
  ActiveLead,
  EmailHistoryEntry,
  TimelineEntry,
} from "./types";

export const ACTIVE_LEADS_MOCK: ActiveLead[] = [
  {
    id: "lead-1",
    title: "Budesonide Respule Supply — ABC Pharma",
    companyName: "ABC Pharma Pvt Ltd",
    contactName: "Rajesh Mehta",
    contactRole: "Purchase Manager",
    contactEmail: "rajesh.mehta@abcpharma.example.com",
    matchedSalt: "Budesonide",
    matchedMedicine: "Budecort Respules",
    dosageForm: "Respules",
    location: "Mumbai, Maharashtra",
    stage: "Follow-up Sent",
    leadScore: 82,
    assignedTo: "Priya Sharma",
    followUpDate: "2026-06-05",
    lastActivity: "2026-06-02",
    notes: "Interested in monthly 25kg API supply. Awaiting pricing sheet.",
    createdAt: "2026-05-18",
  },
  {
    id: "lead-2",
    title: "Budesonide MDI Partnership — Respira Pharma",
    companyName: "Respira Pharma Pvt Ltd",
    contactName: "Anita Desai",
    contactRole: "Head of Institutional Sales",
    contactEmail: "anita.desai@respirapharma.example.com",
    matchedSalt: "Budesonide",
    matchedMedicine: "Pulmicort-class respules",
    dosageForm: "Respules",
    location: "Ahmedabad, Gujarat",
    stage: "Replied",
    leadScore: 85,
    assignedTo: "Priya Sharma",
    followUpDate: "2026-06-04",
    lastActivity: "2026-06-03",
    notes: "Requested COA and stability data for EU filing support.",
    createdAt: "2026-05-12",
  },
  {
    id: "lead-3",
    title: "MENA Export — Global Inhale Exports",
    companyName: "Global Inhale Exports",
    contactName: "Vikram Patel",
    contactRole: "Export Manager",
    contactEmail: "exports@globalinhale.example.com",
    matchedSalt: "Budesonide",
    matchedMedicine: "Budecort Respules",
    dosageForm: "Respules",
    location: "Vadodara, Gujarat",
    stage: "Intro Email Sent",
    leadScore: 65,
    assignedTo: "Arjun Nair",
    followUpDate: "2026-06-07",
    lastActivity: "2026-05-30",
    notes: "First intro sent with respule portfolio deck.",
    createdAt: "2026-05-28",
  },
  {
    id: "lead-4",
    title: "Inhaler Co-marketing — AeroLung Formulations",
    companyName: "AeroLung Formulations",
    contactName: "Suresh Iyer",
    contactRole: "Business Development",
    contactEmail: "bd@aerolung.example.com",
    matchedSalt: "Budesonide",
    matchedMedicine: "Foracort Inhaler",
    dosageForm: "Inhaler",
    location: "Mumbai, Maharashtra",
    stage: "Quotation Sent",
    leadScore: 72,
    assignedTo: "Arjun Nair",
    followUpDate: "2026-06-06",
    lastActivity: "2026-06-01",
    notes: "Quotation v2 shared for 10k unit pilot batch.",
    createdAt: "2026-04-22",
  },
  {
    id: "lead-5",
    title: "PulmoCare API Trial Batch",
    companyName: "PulmoCare Laboratories",
    contactName: "Dr. Kavitha Rao",
    contactRole: "Technical Director",
    contactEmail: "kavitha.rao@pulmocare.example.com",
    matchedSalt: "Budesonide",
    matchedMedicine: "Pulmicort Respules",
    dosageForm: "Respules",
    location: "Hyderabad, Telangana",
    stage: "Sample Requested",
    leadScore: 78,
    assignedTo: "Priya Sharma",
    followUpDate: "2026-06-08",
    lastActivity: "2026-06-02",
    notes: "Sample shipment scheduled for next week.",
    createdAt: "2026-05-05",
  },
  {
    id: "lead-6",
    title: "Montelukast Granules — SunResp Formulations",
    companyName: "SunResp Formulations",
    contactName: "Meera Joshi",
    contactRole: "Procurement Lead",
    contactEmail: "procurement@sunresp.example.com",
    matchedSalt: "Montelukast",
    matchedMedicine: "Montair Granules",
    dosageForm: "Granules",
    location: "Pune, Maharashtra",
    stage: "Verified",
    leadScore: 58,
    assignedTo: "Arjun Nair",
    followUpDate: "2026-06-09",
    lastActivity: "2026-05-27",
    notes: "Contact verified via LinkedIn and company switchboard.",
    createdAt: "2026-05-25",
  },
  {
    id: "lead-7",
    title: "Formoterol DPI Supply — BreathWell Pharma",
    companyName: "BreathWell Pharma",
    contactName: "Amit Khanna",
    contactRole: "Purchase Manager",
    contactEmail: "amit.khanna@breathwell.example.com",
    matchedSalt: "Formoterol",
    matchedMedicine: "Foradil DPI",
    dosageForm: "DPI",
    location: "Delhi NCR",
    stage: "Negotiation",
    leadScore: 74,
    assignedTo: "Priya Sharma",
    followUpDate: "2026-06-03",
    lastActivity: "2026-06-03",
    notes: "Negotiating MOQ and payment terms for annual contract.",
    createdAt: "2026-04-10",
  },
  {
    id: "lead-8",
    title: "Salbutamol Syrup — MediSource Traders",
    companyName: "MediSource Traders",
    contactName: "Rohit Banerjee",
    contactRole: "Trader",
    contactEmail: "rohit@medisource.example.com",
    matchedSalt: "Salbutamol",
    matchedMedicine: "Asthalin Syrup",
    dosageForm: "Syrup",
    location: "Kolkata, West Bengal",
    stage: "Dormant",
    leadScore: 38,
    assignedTo: "Arjun Nair",
    followUpDate: "2026-07-01",
    lastActivity: "2026-03-15",
    notes: "No response after two follow-ups. Revisit in Q3.",
    createdAt: "2026-02-20",
  },
  {
    id: "lead-9",
    title: "Tiotropium DPI — AeroMist Devices",
    companyName: "AeroMist Devices Pvt Ltd",
    contactName: "Neha Gupta",
    contactRole: "Supply Chain Manager",
    contactEmail: "neha.gupta@aeromist.example.com",
    matchedSalt: "Tiotropium",
    matchedMedicine: "Tiova DPI",
    dosageForm: "DPI",
    location: "Bengaluru, Karnataka",
    stage: "Won",
    leadScore: 88,
    assignedTo: "Priya Sharma",
    followUpDate: "—",
    lastActivity: "2026-05-20",
    notes: "PO received for 12-month supply agreement.",
    createdAt: "2026-01-08",
  },
  {
    id: "lead-10",
    title: "Cetirizine Tablets — AllergyCare Labs",
    companyName: "AllergyCare Labs",
    contactName: "Sanjay Verma",
    contactRole: "Commercial Head",
    contactEmail: "sanjay@allergycare.example.com",
    matchedSalt: "Cetirizine",
    matchedMedicine: "Cetzine Tablets",
    dosageForm: "Tablet",
    location: "Indore, Madhya Pradesh",
    stage: "Lost",
    leadScore: 45,
    assignedTo: "Arjun Nair",
    followUpDate: "—",
    lastActivity: "2026-04-18",
    notes: "Chose incumbent supplier on price.",
    createdAt: "2026-03-01",
  },
  {
    id: "lead-11",
    title: "Levocetirizine Syrup — HistFree Pharma",
    companyName: "HistFree Pharma",
    contactName: "Pooja Nambiar",
    contactRole: "BD Manager",
    contactEmail: "pooja@histfree.example.com",
    matchedSalt: "Levocetirizine",
    matchedMedicine: "Levocet Syrup",
    dosageForm: "Syrup",
    location: "Chennai, Tamil Nadu",
    stage: "Saved",
    leadScore: 52,
    assignedTo: "Priya Sharma",
    followUpDate: "2026-06-10",
    lastActivity: "2026-06-03",
    notes: "Saved from Lead Discovery — pending verification.",
    createdAt: "2026-06-03",
  },
  {
    id: "lead-12",
    title: "Ambroxol API — ClearAir Chemicals",
    companyName: "ClearAir Chemicals",
    contactName: "Imran Sheikh",
    contactRole: "Purchase Manager",
    contactEmail: "imran@clearair.example.com",
    matchedSalt: "Ambroxol",
    matchedMedicine: "Mucosolvan Syrup",
    dosageForm: "Syrup",
    location: "Surat, Gujarat",
    stage: "Intro Email Sent",
    leadScore: 61,
    assignedTo: "Arjun Nair",
    followUpDate: "2026-06-11",
    lastActivity: "2026-06-01",
    notes: "Salt-specific outreach template used.",
    createdAt: "2026-05-29",
  },
];

const TIMELINE_BY_LEAD: Record<string, TimelineEntry[]> = {
  "lead-1": [
    {
      id: "t1",
      date: "2026-06-02",
      title: "Follow-up email sent",
      description: "Reminder on pricing sheet and MOQ options.",
      type: "email",
    },
    {
      id: "t2",
      date: "2026-05-25",
      title: "Stage: Follow-up Sent",
      description: "Moved from Intro Email Sent after no reply in 7 days.",
      type: "stage",
    },
    {
      id: "t3",
      date: "2026-05-20",
      title: "Intro email sent",
      description: "First Introduction template with Budesonide focus.",
      type: "email",
    },
  ],
};

const EMAILS_BY_LEAD: Record<string, EmailHistoryEntry[]> = {
  "lead-1": [
    {
      id: "e1",
      date: "2026-06-02",
      subject: "Re: Budesonide respule supply — pricing follow-up",
      direction: "outbound",
      preview: "Hi Rajesh, following up on our discussion regarding monthly supply…",
    },
    {
      id: "e2",
      date: "2026-05-28",
      subject: "Budesonide respule supply opportunity",
      direction: "inbound",
      preview: "Thanks for reaching out. Please share your product catalog and COA…",
    },
  ],
};

export function getLeadTimeline(leadId: string): TimelineEntry[] {
  return (
    TIMELINE_BY_LEAD[leadId] ?? [
      {
        id: "default",
        date: "2026-06-01",
        title: "Lead created",
        description: "Lead saved from discovery workflow.",
        type: "stage",
      },
    ]
  );
}

export function getLeadEmailHistory(leadId: string): EmailHistoryEntry[] {
  return EMAILS_BY_LEAD[leadId] ?? [];
}

export function getUniqueAssignees(leads: ActiveLead[]): string[] {
  return [...new Set(leads.map((l) => l.assignedTo))].sort();
}

export function getUniqueSalts(leads: ActiveLead[]): string[] {
  return [...new Set(leads.map((l) => l.matchedSalt))].sort();
}
